Wrong number of arguments: call(foo,[1,2])